Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "alright." is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "as" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "ty" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "np" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "you" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "it" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "hm" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "got" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "did" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yes" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "i" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "this" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "basically" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "huh" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "let" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "says" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "that's" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "oh" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "F" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "also" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "just" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "wow" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yep" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "need" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "no" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yeah" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "nice" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "one" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "nice" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "took" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "what's" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "it" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "i" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yeah" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "don't" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "oh" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "should" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "wrong" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "indeed" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "o" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "this" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "you" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yeah..." is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "forgot" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yeah" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "it" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "i" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "shouldn't" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "i" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "because" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "well" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "it's" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "you" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "merge" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "oh" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "never" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "i've" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "guess" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yeah" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Schep**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "actually" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "since" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "wait" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Bear**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxi**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxibear**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Bear**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxi**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxibear**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "copied" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "so" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxi**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxibear**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "nice" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "one" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "yay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "nice" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "ty" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "ya" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "mmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "k" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "ok" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "<:nice:407538895337816065>" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "Nice" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "uh" is not found
Ignoring exception in command mk
Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 98, in mk
    out = generate_markov(args)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 83, in generate_markov
    text_model = markovify.combine(models)
  File "/usr/local/lib/python3.6/dist-packages/markovify/utils.py", line 28, in combine
    raise ValueError("All `models` must have the same state size.")
ValueError: All `models` must have the same state size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: All `models` must have the same state size.
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "uh" is not found
Ignoring exception in command mk
Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 98, in mk
    out = generate_markov(args)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 83, in generate_markov
    text_model = markovify.combine(models)
  File "/usr/local/lib/python3.6/dist-packages/markovify/utils.py", line 28, in combine
    raise ValueError("All `models` must have the same state size.")
ValueError: All `models` must have the same state size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: All `models` must have the same state size.
Ignoring exception in command mk
Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 98, in mk
    out = generate_markov(args)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 83, in generate_markov
    text_model = markovify.combine(models)
  File "/usr/local/lib/python3.6/dist-packages/markovify/utils.py", line 28, in combine
    raise ValueError("All `models` must have the same state size.")
ValueError: All `models` must have the same state size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: All `models` must have the same state size.
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "you're" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "markovify" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "'" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxi**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**MemersMarkov**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Coizioc**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "trying" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "lemme" is not found
Logged in as MemersMarkov (ID:408587496033878017) | Connected to 2 servers | Connected to 78 users
--------
Current Discord.py Version: 0.16.8 | Current Python Version: 3.6.3
--------
Use this link to invite MemersMarkov:
https://discordapp.com/oauth2/authorize?client_id=408587496033878017&scope=bot&permissions=8
--------
Support Discord Server: https://discord.gg/FNNNgqb
Github Link: https://github.com/Habchy/BasicBot
--------
You are running BasicBot v2.1
Created by Habchy#1665
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Coizioc**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxi+Gynecoiogist**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Casal**:" is not found
Ignoring exception in command mk
Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 98, in mk
    out = generate_markov(args)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 83, in generate_markov
    text_model = markovify.combine(models)
  File "/usr/local/lib/python3.6/dist-packages/markovify/utils.py", line 28, in combine
    raise ValueError("All `models` must have the same state size.")
ValueError: All `models` must have the same state size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: All `models` must have the same state size.
Ignoring exception in command mk
Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 98, in mk
    out = generate_markov(args)
  File "/home/austin/Documents/MemersMarkov/MemersMarkov.py", line 83, in generate_markov
    text_model = markovify.combine(models)
  File "/usr/local/lib/python3.6/dist-packages/markovify/utils.py", line 28, in combine
    raise ValueError("All `models` must have the same state size.")
ValueError: All `models` must have the same state size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: All `models` must have the same state size.
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Coizioc**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Casal**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Coizioc**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "rmk" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "**Raxi+Casal+Gynecoiogist**:" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "okay" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "up" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "also" is not found
Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "instead" is not found
